name: client_control
description: Client control example to use provider state management



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  provider: ^6.0.3

dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^1.0.0






flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
